### PR TITLE
Polishing

### PR DESCRIPTION
**Pull request by corinnekrych**
to get a closer look and feel across natives app:
- add icon for logged-in view similar to android
- add activity spinning
- remove close button from webview
  @danielpassos @edewit mind to review?

### CODE REVIEW

**Comment by edewit** [comment]
:+1: but add the "sign in again" button to demonstrate that the user only needs to provide a password once

**Comment by corinnekrych** [comment]
@edewit i've just added it again see https://github.com/corinnekrych/saml-ios-app/commit/48d670213417e5550eb4f77aa517ef6a5943075f1
Although not that visual becuse you stay on the same screen...
But i've added some Debug Logging.

**Comment by edewit** [comment]
@corinnekrych I just do the same thing that the sign in button does:
https://github.com/feedhenry-templates/saml-windows-app/blob/master/saml-windows/saml-windows.Shared/MainPage.xaml#L41

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
